//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SiewebEntities : DbContext
{
    public SiewebEntities()
        : base("name=SiewebEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<admins> admins { get; set; }
    public DbSet<faqs> faqs { get; set; }
    public DbSet<files> files { get; set; }
    public DbSet<news> news { get; set; }
    public DbSet<pages> pages { get; set; }
    public DbSet<pics> pics { get; set; }
    public DbSet<teacher> teacher { get; set; }
}
