//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class admins
{
    public int id { get; set; }
    public string account { get; set; }
    public string password { get; set; }
    public System.DateTime createtime { get; set; }
    public System.DateTime updatetime { get; set; }
}

public partial class faqs
{
    public int id { get; set; }
    public string sname { get; set; }
    public string title { get; set; }
    public string body { get; set; }
    public System.DateTime createtime { get; set; }
    public System.DateTime updatetime { get; set; }
    public string reply { get; set; }
    public int state { get; set; }
}

public partial class files
{
    public int id { get; set; }
    public string title { get; set; }
    public string filename { get; set; }
    public System.DateTime createtime { get; set; }
}

public partial class news
{
    public int id { get; set; }
    public string title { get; set; }
    public string body { get; set; }
    public System.DateTime updatetime { get; set; }
    public System.DateTime createtime { get; set; }
    public int newclass { get; set; }
}

public partial class pages
{
    public int id { get; set; }
    public string title { get; set; }
    public string body { get; set; }
    public System.DateTime createtime { get; set; }
    public System.DateTime updatetime { get; set; }
    public int belong { get; set; }
}

public partial class teachers
{
    public int id { get; set; }
    public string tname { get; set; }
    public string phone { get; set; }
    public string title { get; set; }
    public string body { get; set; }
    public System.DateTime updatetime { get; set; }
    public System.DateTime createtime { get; set; }
    public string place { get; set; }
    public string describe { get; set; }
    public string email { get; set; }
}
